Timing
CQCL/pytket-phir pull request #134
Opened 2024-02-20 14:47 UTC by Asa-Kosto-QTM

# Description

Updated timing data and added a function that reliably brings PHIR estimated transport time to within 10-15% of the true transport time.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ X] I have performed a self-review of my code
- [ ] I have added tests that prove my fix is effective or that my feature works <- N/A, all tests require internal resources for verification.

2024-02-20 16:01 UTC, qartik requested changes

2024-02-20 16:20 UTC, Asa-Kosto-QTM commented on pytket/phir/machine.py
> +    measurement_prep_transport_time: float
i think there should be some indication that it is transport specifically to prepare for measurement, not the measurement itself. maybe meas_prep_time?

2024-02-20 16:30 UTC, qartik commented on pytket/phir/machine.py
> +    measurement_prep_transport_time: float
That works too. I wasn't sure of the importance of all the keywords in there.

2024-02-20 17:55 UTC, qartik commented on pytket/phir/phirgen_parallel.py
> +            op["duration"] = transport_info
How about this?
```suggestion
            duration, units = op["duration"]
            op["duration"] = duration + adjustment, units
```

2024-02-20 17:55 UTC, qartik submitted a review, later dismissed
Looking good, leaving a minor suggestion.

2024-02-21 20:54 UTC, qartik submitted a review, later dismissed

2024-03-04 21:35 UTC, qciaran approved these changes
![Alt Text](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ3NramZyOXZ2bm5oaHBhd3F1aDJwaTdleWRicDlrc2h6dGUwdXRzYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/XreQmk7ETCak0/giphy.gif)
LGTM
Code seems minimal and sensical. Output looks as expected on my end.

2024-03-06 17:41 UTC, neal-erickson requested changes
Waiting on feedback from Alex

2024-03-06 19:30 UTC, qartik approved these changes

2024-03-06 23:14 UTC, closed without merging