Make machine argument optional
CQCL/pytket-phir pull request #18
Opened 2023-10-25 16:38 UTC by Asa-Kosto-QTM

allow full e2e use without specifying a machine object

2023-10-25 16:50 UTC, qartik requested changes
Looking good. Left one suggestion.

2023-10-25 16:50 UTC, qartik commented on pytket/phir/api.py
> +        placed = place_and_route(shards, machine)
Consider:
```diff
-    if machine:
-        logger.debug("Performing placement and routing...")
-        placed = place_and_route(shards, machine)
-    else:
-        placed = place_and_route(shards, machine)
+    logger.debug("Performing placement and routing...")
+    placed = place_and_route(shards, machine)
```

2023-10-25 19:41 UTC, qartik approved these changes

2023-10-26 15:30 UTC, peter-campora approved these changes
Looks good. Will be nice to see the test cases in test_api get fleshed out a bit more later.

2023-10-26 16:57 UTC, merged