Add support for `ClExprOp`
CQCL/pytket-phir pull request #251
Opened 2024-10-30 13:19 UTC by cqc-alec

# Description

Closes #250 .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the changelog with any user-facing changes

2024-11-01 20:19 UTC, qartik requested changes
Correctness looks good. I noticed that some of the ruff ignored can be resolved fairly easily. I am including a patch.

I also noticed that the comments from ClExpr's are not super helpful as they don't emit the expression. In my patch, I have them show up like so:
```
ClExpr a[0], a[1], d[0] of the form lsh(r0, 1)
```
Ideally the `str` version of these expressions should carry the expression.
[ClExpr.patch](https://github.com/user-attachments/files/17603853/ClExpr.patch)

2024-11-01 20:19 UTC, qartik commented on pytket/phir/phirgen.py
> +            logging.exception("Classical operation %s unsupported by PHIR", str(op))
This match case could be extracted into its own function.

2024-11-04 14:44 UTC, cqc-alec commented
Thanks for the suggestions @qartik . Have applied your patch and implemented most suggestions. Leaving the `assert` as is, otherwise mypy complains (and I think `assert` is reasonable since it really must be this type by construction).

2024-11-04 15:00 UTC, qartik approved these changes

2024-11-04 15:08 UTC, merged