RZ/R1XY order swapping
CQCL/pytket-phir pull request #82
Opened 2024-01-09 19:39 UTC by Asa-Kosto-QTM

fixing a bug that showed up in the rxrz.qasm circuit where the relative ordering of subcommands was not preserved.

2024-01-09 21:43 UTC, qartik reviewed
Minor suggestions, looking good otherwise.

2024-01-09 21:43 UTC, qartik commented on pytket/phir/phirgen_parallel.py
>      # and all other gates will go in %3=2 groups
```suggestion
    # RZ gates go in (mod 3)=0 groups, R1XY gates go in (mod 3)=1 groups,
    # and all other gates will go in (mod 3)=2 groups
```
Minor suggestion, perhaps easier to read this way.

2024-01-09 21:43 UTC, qartik commented on tests/test_parallel_subcommand_relative_ordering.py
> +# Copyright (c) 2023 Quantinuum LLC All rights reserved.
```suggestion
# Copyright (c) 2024 Quantinuum LLC All rights reserved.
```

2024-01-09 21:43 UTC, qartik commented on tests/test_parallel_subcommand_relative_ordering.py
Can the contents of this file be part of the existing `test_parallelization.py`?

2024-01-09 21:54 UTC, Asa-Kosto-QTM commented on tests/test_parallel_subcommand_relative_ordering.py
In theory it could, I made it separate because it uses a different qasm file and the thing it is testing is not the json parallel output per se, just that the ordering stays the same when genphir_parallel is used. Easy enough to switch, though.

2024-01-09 22:10 UTC, qciaran submitted a review, later dismissed
LGTM This solves the issue I had on my side.

2024-01-10 13:21 UTC, qartik commented on tests/test_parallel_subcommand_relative_ordering.py
I think I prefer it as part of the parallel testing file. We don't need to proliferate too many test files with a single test each. A good rule of thumb is to have one test file per module.

2024-01-10 13:21 UTC, qartik requested changes
Just need to move the test into existing test file.

2024-01-10 15:47 UTC, qartik commented on pytket/phir/cli.py
> +# mypy: disable-error-code="misc"
Could you remove this unnecessary change from this PR?

2024-01-10 15:52 UTC, qartik approved these changes

2024-01-10 16:19 UTC, merged